todoproject/todoapp/urls.py
from django.contrib import admin
from . import views
from django.urls import path

app_name = 'todolist'

urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.Taskdetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteview.as_view(),name='cbvdelete'),



]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from todoproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    name=models.CharField(max_length=250)
    priority= models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from . models import Task

from django import forms


class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
import django.shortcuts
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

from .forms import TodoForm
from .models import Task


class Tasklistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task'


class Taskdetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'


class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todolist:cbvdetail', kwargs={'pk': self.object.id})

class TaskDeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todolist:cbvhome')

def add(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return django.shortcuts.render(request, "home.html", {'task': task1})


def delete(request, id):
    task = Task.objects.get(id=id)
    if request.method == 'POST':
        task.delete()
        return django.shortcuts.redirect('/')
    return django.shortcuts.render(request, "delete.html")


def update(request, id):
    task = Task.objects.get(id=id)
    f = TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return django.shortcuts.redirect('/')
    return django.shortcuts.render(request, "edit.html", {'f': f, 'task': task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure this task is to done?</p>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}
            <div class="shadow card">
                <div class="card-body">
                        <h5 class="card-title">{{task.name}}</h5>
                        <p>{{task.priority}}</p>
                        <p>{{task.date}}</p>
                        <a class="btn btn-danger" href="{% url 'todolist:delete' task.id %}">Done</a>
                        <a class="btn btn-success" href="{% url 'todolist:update' task.id %}">Update</a>
                    </div>
                </div>

{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
          <div class="banner">
              <div class="banner-text">
                  <h1>ToDo</h1>
              </div>
          </div>
      </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="p-3 shadow">
        {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control" name="task" placeholder="Taskname">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="priority" placeholder="Priority">
    </div>
     <div class="form-group">
        <input type="date" class="form-control" name="date" placeholder="Enter your date">
    </div>
            <input type="submit" class="btn btn-success">
        </form>
        </div>




        <div class="col-md-6">
            {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p>{{i.priority}}</p>
                        <p>{{i.date}}</p>
                        <a class="btn btn-danger" href="{% url 'todolist:delete' i.id %}">Done</a>
                        <a class="btn btn-success" href="{% url 'todolist:update' i.id %}">Update</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}